#cloud-config
package_update: true
packages:
  - docker.io
  - docker-compose-v2
  - unattended-upgrades
ssh_pwauth: false
write_files:
  - path: /etc/ssh/sshd_config.d/00-valheim.conf
    permissions: '0644'
    content: |
      PasswordAuthentication no
      PermitRootLogin prohibit-password
runcmd:
  - [systemctl, enable, --now, docker]
  - [systemctl, restart, ssh]
  - [install, -d, -m, '0700', /opt/valheim]
